AllCops:
  Include:
    - Cheffile
    - Gemfile
    - Rakefile
  Exclude:
   - cookbooks/**
   - tmp/**

SingleSpaceBeforeFirstArg:
  Enabled: false # Useful for more readable alignment of method call args
